matrix:
  include:
    - language: android
      sudo: required
      env:
        - NAME=Android
        global:
          - ANDROID_API=23
          - ANDROID_BUILD_TOOLS=23.0.1
          - ANDROID_ABI=armeabi-v7a
          - ANDROID_TAG=google_apis
          - ADB_INSTALL_TIMEOUT=5 # minutes
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-$ANDROID_BUILD_TOOLS
          - android-$ANDROID_API
          - extra-android-support
          - sys-img-$ANDROID_ABI-android-$ANDROID_BUILD_TOOLS
      before_script:
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - npm install
        - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$ANDROID_API --abi $ANDROID_ABI --tag $ANDROID_TAG
      script:
        - cd android && ./gradlew assemble && cd ..
        - ./scripts/testAndroid.sh
