matrix:
  include:
    - language: android
      sudo: required
      dist: precise
      env:
        - NAME=Android-23
        - DIST=precise
        - ANDROID_TARGET=android-23
        - ANDROID_API=23
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_BUILD_TOOLS=23.0.1
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_TAG=google_apis
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-$ANDROID_BUILD_TOOLS
          - android-$ANDROID_API
          - extra-android-support
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - sys-img-$ANDROID_ABI-$ANDROID_TAG-$ANDROID_API
      before_script:
        - android list sdk --extended --no-ui --all
        - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --tag $ANDROID_TAG
        - emulator -avd test -no-skin -no-audio -no-window &
        - adb wait-for-device
        - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y nodejs
        - npm install
      script:
        - cd android && ./gradlew assemble && cd ..
        - ./scripts/testAndroid.sh
